### PR TITLE
New Feature: use own HipChat server

### PR DESCRIPTION
**Pull request by droberin**
This would allow users to set the HipChat server they want to instead of main one.

### CODE REVIEW

**Comment by hugorodgerbrown** [comment]
Thanks @droberin will release to PyPI in due course.

**Comment by droberin** [comment]
My pleasure, sir. Thank you for releasing.

**Comment by hugorodgerbrown** [comment]
Released as v0.4.

**Review by droberin — COMMENTED** [review]
I'm affraid I made a mistake!!!! :(
Wrong env name in the code, one points at 'HIPCHAT_API_SERVER' but then it reads from 'HIPCHAT_SERVER' instead.
Must be both set to 'HIPCHAT_API_SERVER'. Without replacing this line, a user must set both env vars to achieve the wanted result.

**Comment by hugorodgerbrown** [comment]
:-)

fixed and pushed as 0.4.1

**Pull request merged**
